version = 1
SPDX-PackageName = "GitHub OIDC Federation"
SPDX-PackageSupplier = "The Gardener project <gardener@googlegroups.com>"
SPDX-PackageDownloadLocation = "https://github.com/gardener/github-oidc-federation"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Contributors to the Gardener project"
SPDX-License-Identifier = "Apache-2.0"
